required = ["github.com/golang/protobuf/protoc-gen-go"]

[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  #revision = "1e59b77b52bf8e4b449a57e6f79f21226d571845" # recent versions introduce breaking changes
  version = "v1.1.0"
